# Generated by Django 5.2.1 on 2025-06-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cadastro_usuario', '0002_remove_usuario_id_usuario_id_usuario'),
        ('games', '0005_alter_game_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGamesByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(blank=True, to='games.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_cadastro_usuario.usuario')),
            ],
        ),
    ]
