# Generated by Django 5.2.1 on 2025-07-12 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_biblioteca', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritegamesbyuser',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.game'),
        ),
        migrations.AddField(
            model_name='favoritegamesbyuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
