# Generated by Django 5.2.1 on 2025-07-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0002_initial'),
        ('games', '0002_alter_rating_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritegamesbyuser',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='savedInLibrary', to='games.game'),
        ),
    ]
