<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-07-15 01:05
=======
# Generated by Django 5.2.1 on 2025-07-15 00:37
>>>>>>> 70e640adc5412e0f364d04efbb4f4bf5340f13d2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
