# Generated by Django 5.2.1 on 2025-07-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
