# Generated by Django 5.2.1 on 2025-05-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(null=True, upload_to='gamesupload/'),
        ),
    ]
