# Generated by Django 5.2.1 on 2025-05-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
    ]
